//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gui.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gui.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to convert error!.
        /// </summary>
        internal static string ConvErr {
            get {
                return ResourceManager.GetString("ConvErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert ok!.
        /// </summary>
        internal static string ConvOk {
            get {
                return ResourceManager.GetString("ConvOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel exported XML (*.xml)|*.xml.
        /// </summary>
        internal static string GuiRes {
            get {
                return ResourceManager.GetString("GuiRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File openred!.
        /// </summary>
        internal static string OpenedFile {
            get {
                return ResourceManager.GetString("OpenedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error open file.
        /// </summary>
        internal static string OpnFileErr {
            get {
                return ResourceManager.GetString("OpnFileErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error save file.
        /// </summary>
        internal static string SavErr {
            get {
                return ResourceManager.GetString("SavErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save ok!.
        /// </summary>
        internal static string SavOk {
            get {
                return ResourceManager.GetString("SavOk", resourceCulture);
            }
        }
    }
}
